### ISSUE TITLE
try using Marcus's wq-dash as starting point

### ISSUE THREAD

**Issue by 7yl4r** [USF-IMARS/old-fl-coral-reef-fcr-water-quality-dashboard#2]
https://github.com/7yl4r/wq-dash

* [x] comment out parts of the site we don't need
* [x] comment out plots we don't need
* [x] replace Rdat files

**Comment by 7yl4r** [comment]
@dotis : I was able to cut a lot and swap out the data. Here is what it looks like:

![image](https://user-images.githubusercontent.com/1051390/235281786-211921ab-ba92-484f-80c4-12354d122f29.png)

**Comment by dotis** [comment]
Looks great. This station map is really full. Perhaps we should find a way to subset by region (Biscayne Bay, Keys, West Florida Shelf, etc.)
